apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-preparo-config
data:
  DATABASE_URL: jdbc:mysql://goodburguer.c8nvenlrrp9x.us-east-1.rds.amazonaws.com:3306/goodburguer_preparo
  MYSQL_DATABASE: goodburguer
  DATABASE_PASSWORD: Y6nX4nJrtOW7vyVNLfUe
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-preparo-secret
type: Opaque
data:
  DATABASE_USERNAME: YWRtaW4=
  DATABASE_PASSWORD: WXZuWDRuSmpydE9XN3Z5Uk5MZlVl