apiVersion: v1
kind: Service
metadata:
  name: goodburguer-preparo-service
  labels:
    app: goodburguer-preparo-app
spec:
  type: LoadBalancer
  selector:
    app: goodburguer-preparo-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080